# SPDX-License-Identifier: GPL-3.0-only
---
- hosts:
    - edge.sea1.wobscale.website
  vars:
    users: [ilianaw, esk]
  become_method: doas
  tasks:
    - name: install ports
      openbsd_pkg: name={{ item }} state=present
      with_items:
        - ansible
        - git
        - htop
        - screen--
        - vim--no_x11
    ### Tasks that require hitting the internet must go above this line ###
    - name: delete /etc/resolv.conf
      file: path=/etc/resolv.conf state=absent
    - name: get kern.version
      shell: 'sysctl -n kern.version | sed 1q'
      register: kern_version
      changed_when: False
      check_mode: no
    - name: sshd PasswordAuthentication=no
      lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no" state=present
      notify: restart sshd
    - name: empty /root/.ssh/authorized_keys
      copy: src=empty dest=/root/.ssh/authorized_keys owner=root group=wheel mode=0600
    - name: set up users
      user: name={{ item }} groups=wheel
      with_items: "{{ users }}"
    - name: set up authorized_keys
      authorized_key: user={{ item }} key={{ lookup('file', 'files/ssh/' + item) }} state=present
      with_items: "{{ users }}"
    - name: rc.conf.local
      copy: src=files/rc.conf.local dest=/etc/rc.conf.local owner=root group=wheel mode=0644
    - name: hostname files
      copy: src=files/hostname.{{ item }} dest=/etc/hostname.{{ item }} owner=root group=wheel mode=0640
      with_items:
        - em0
        - em1
        - vlan10
        - vlan12
        - vlan20
        - vlan255
    - name: doas.conf
      copy: src=files/doas.conf dest=/etc/doas.conf owner=root group=wheel mode=0600
    - name: bgpd.conf
      copy: src=files/bgpd.conf dest=/etc/bgpd.conf owner=root group=wheel mode=0600
    - name: dhcpd.conf
      copy: src=files/dhcpd.conf dest=/etc/dhcpd.conf owner=root group=wheel mode=0644
    - name: rtadvd.conf
      copy: src=files/rtadvd.conf dest=/etc/rtadvd.conf owner=root group=wheel mode=0644
    - name: sysctl.conf
      copy: src=files/sysctl.conf dest=/etc/sysctl.conf owner=root group=wheel mode=0644
    - name: motd
      template: src=templates/motd.j2 dest=/etc/motd owner=root group=operator mode=0664
    - name: installurl
      copy: src=files/installurl dest=/etc/installurl owner=root group=wheel mode=0644
  handlers:
    - name: restart sshd
      service: name=sshd state=restarted
